services:
  postgres:
    image: postgres:15
    container_name: postgres_auth
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: hrms_userAuthDB   # ✅ This auto-creates the DB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
